"""empty message

Revision ID: 580947e11125
Revises: a568e5d96bce
Create Date: 2020-04-23 17:14:34.295432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580947e11125'
down_revision = 'a568e5d96bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'price')
    # ### end Alembic commands ###
